name: Build raylib Libraries

on: [workflow_dispatch]

jobs:
  build:
    uses: JunaMeinhold/cmake-actions/.github/workflows/cmake.yml@v1.x.x
    with:
      lib-name: "raylib"
      repo: "raysan5/raylib"
      repo-tag: "6.0"
      cmake-flags: "-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF"
      cmake-flags-windows: "-DCMAKE_SYSTEM_VERSION=10.0.26100.0"
      cmake-flags-android: "-DPLATFORM=Android -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--unresolved-symbols=ignore-all"
      linux-deps: "build-essential cmake libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev"
      ndk-version: "26.3.11579264"
      bin-name-osx: "raylib/libraylib.dylib"
      bin-name-linux: "raylib/libraylib.so"
      bin-name-android: "raylib/libraylib.so"
      bin-name-windows: "raylib/Release/raylib.dll"
      bin-name-osx-normalized: "libraylib.dylib"
      bin-name-linux-normalized: "libraylib.so"
      bin-name-android-normalized: "libraylib.so"
      bin-name-windows-normalized: "raylib.dll"

  create-pr:
    needs: [build]
    uses: JunaMeinhold/cmake-actions/.github/workflows/create-pr.yml@v1.x.x
    with:
      lib-name: "raylib"
      lib-version: "6.0"
      pr-base-branch: "main"
      pr-reviewers: JunaMeinhold
      pr-branch: raylib-artifacts
